import { Language } from './types';

export const TEXTS: Record<Language, Record<string, string>> = {
  en: {
    appTitle: "MuseSpark",
    welcome: "Ignite your imagination.",
    welcomeSub: "Collaborate with AI to turn your fleeting thoughts into structured reality.",
    startChat: "New Spark",
    login: "Login / Register",
    history: "Journal",
    myInspirations: "My Portfolio",
    settings: "Settings",
    send: "Inspire Me",
    placeholder: "What are you dreaming of today?",
    analyzing: "Connecting dots...",
    generateNote: "Crystallize Idea",
    save: "Save to Portfolio",
    update: "Update Vision",
    back: "Back",
    backToList: "Return to Gallery",
    satisfied: "Save Vision",
    notSatisfied: "Refine",
    legalWarning: "Note: AI generated content. Validate professionally.",
    subscribe: "Go Pro",
    subscriptionDesc: "Unlimited sparks, deeper analysis, and export tools.",
    loginDesc: "Sync your ideas across the cosmos.",
    email: "Email",
    password: "Password",
    signIn: "Enter",
    mvp: "MVP Strategy",
    businessVal: "Business Core",
    risks: "Risk Assessment",
    tags: "Keywords",
    fullScreen: "Focus Mode",
    minimize: "Exit Focus",
    delete: "Delete",
    viewNote: "View Blueprint",
    emptyHistory: "No sparks yet",
    emptyInspirations: "Your portfolio is empty",
    generatedMap: "Visual Map",
    uploadImage: "Add Visual Context",
    translating: "Translating...",
    edit: "Edit",
    cancelEdit: "Cancel",
    proFeature: "Pro",
    subscribeModalTitle: "Upgrade MuseSpark",
    subscribeBtn: "Unlock All - $9.99/mo",
    deleteChatConfirm: "Extinguish this spark?",
    deleteInspirationConfirm: "Remove this vision from portfolio?",
    mindMap: "Mind Map",
    mindMapHelper: "Spark Assist",
    mindMapPlaceholder: "Expand this node...",
    memo: "Scratchpad",
    startersTitle: "Need a spark? Try these:",
  },
  zh: {
    appTitle: "灵感助手",
    welcome: "点燃你的想象力。",
    welcomeSub: "与 AI 协作，将转瞬即逝的想法转化为结构化的现实。",
    startChat: "新灵感",
    login: "登录 / 注册",
    history: "灵感日志",
    myInspirations: "作品集",
    settings: "设置",
    send: "发送",
    placeholder: "今天你想创造什么？",
    analyzing: "正在连接思维...",
    generateNote: "生成方案",
    save: "保存到作品集",
    update: "更新愿景",
    back: "返回",
    backToList: "返回画廊",
    satisfied: "保存愿景",
    notSatisfied: "继续打磨",
    legalWarning: "注：AI生成内容，请寻求专业验证。",
    subscribe: "升级专业版",
    subscriptionDesc: "无限灵感，深度分析，导出工具。",
    loginDesc: "同步你的创意宇宙。",
    email: "邮箱",
    password: "密码",
    signIn: "进入",
    mvp: "MVP 策略",
    businessVal: "商业核心",
    risks: "风险评估",
    tags: "关键词",
    fullScreen: "专注模式",
    minimize: "退出专注",
    delete: "删除",
    viewNote: "查看蓝图",
    emptyHistory: "暂无记录",
    emptyInspirations: "作品集为空",
    generatedMap: "结构图",
    uploadImage: "添加视觉参考",
    translating: "翻译中...",
    edit: "编辑",
    cancelEdit: "取消",
    proFeature: "专业版",
    subscribeModalTitle: "解锁 MuseSpark Pro",
    subscribeBtn: "立即订阅 - ¥28/月",
    deleteChatConfirm: "确定要熄灭这个灵感火花吗？",
    deleteInspirationConfirm: "从作品集中移除此愿景？",
    mindMap: "思维导图",
    mindMapHelper: "灵感助理",
    mindMapPlaceholder: "扩展这个节点...",
    memo: "草稿本",
    startersTitle: "缺乏灵感？试试这些：",
  },
  es: {
    appTitle: "MuseSpark",
    welcome: "Enciende tu imaginación.",
    welcomeSub: "Colabora con IA para convertir pensamientos fugaces en realidad.",
    startChat: "Nueva Chispa",
    login: "Acceder",
    history: "Diario",
    myInspirations: "Portafolio",
    settings: "Ajustes",
    send: "Inspirar",
    placeholder: "¿Qué sueñas hoy?",
    analyzing: "Conectando...",
    generateNote: "Cristalizar",
    save: "Guardar",
    update: "Actualizar",
    back: "Volver",
    backToList: "Galería",
    satisfied: "Guardar",
    notSatisfied: "Refinar",
    legalWarning: "Nota: Contenido IA. Validar profesionalmente.",
    subscribe: "Pro",
    subscriptionDesc: "Chispas ilimitadas y análisis profundo.",
    loginDesc: "Sincroniza tus ideas.",
    email: "Correo",
    password: "Clave",
    signIn: "Entrar",
    mvp: "Estrategia MVP",
    businessVal: "Núcleo",
    risks: "Riesgos",
    tags: "Etiquetas",
    fullScreen: "Enfoque",
    minimize: "Salir",
    delete: "Borrar",
    viewNote: "Ver Plano",
    emptyHistory: "Sin chispas",
    emptyInspirations: "Portafolio vacío",
    generatedMap: "Mapa Visual",
    uploadImage: "Ref. Visual",
    translating: "Traduciendo...",
    edit: "Editar",
    cancelEdit: "Cancelar",
    proFeature: "Pro",
    subscribeModalTitle: "Mejorar MuseSpark",
    subscribeBtn: "Suscribirse - $9.99/mes",
    deleteChatConfirm: "¿Extinguir esta chispa?",
    deleteInspirationConfirm: "¿Eliminar esta visión?",
    mindMap: "Mapa Mental",
    mindMapHelper: "Asistente",
    mindMapPlaceholder: "Expandir...",
    memo: "Bloc",
    startersTitle: "¿Necesitas una chispa?",
  },
  ja: {
    appTitle: "MuseSpark",
    welcome: "想像力を点火する。",
    welcomeSub: "AIと協力して、儚い思考を構造化された現実に変えましょう。",
    startChat: "新しいスパーク",
    login: "ログイン",
    history: "ジャーナル",
    myInspirations: "ポートフォリオ",
    settings: "設定",
    send: "送信",
    placeholder: "今日はどんな夢を描きますか？",
    analyzing: "接続中...",
    generateNote: "結晶化",
    save: "保存",
    update: "更新",
    back: "戻る",
    backToList: "ギャラリー",
    satisfied: "保存",
    notSatisfied: "洗練",
    legalWarning: "注：AI生成コンテンツ。専門的に検証してください。",
    subscribe: "Proへ",
    subscriptionDesc: "無制限のスパーク、深い分析。",
    loginDesc: "アイデアを同期。",
    email: "メール",
    password: "パスワード",
    signIn: "入る",
    mvp: "MVP戦略",
    businessVal: "ビジネスコア",
    risks: "リスク",
    tags: "タグ",
    fullScreen: "集中",
    minimize: "戻る",
    delete: "削除",
    viewNote: "設計図を見る",
    emptyHistory: "履歴なし",
    emptyInspirations: "ポートフォリオは空です",
    generatedMap: "ビジュアルマップ",
    uploadImage: "画像追加",
    translating: "翻訳中...",
    edit: "編集",
    cancelEdit: "キャンセル",
    proFeature: "Pro",
    subscribeModalTitle: "MuseSpark Pro",
    subscribeBtn: "登録 - ¥1000/月",
    deleteChatConfirm: "このスパークを消しますか？",
    deleteInspirationConfirm: "このビジョンを削除しますか？",
    mindMap: "マインドマップ",
    mindMapHelper: "アシスタント",
    mindMapPlaceholder: "拡張...",
    memo: "メモ",
    startersTitle: "ヒントが必要ですか？",
  }
};

export const STARTERS: Record<Language, string[]> = {
  en: [
    "A subscription service for rare houseplants",
    "A mobile app connecting local musicians for jam sessions",
    "Eco-friendly packaging made from seaweed",
    "A sci-fi novel about a library at the end of time"
  ],
  zh: [
    "一个稀有室内植物的订阅服务",
    "连接本地音乐家进行即兴演奏的App",
    "用海藻制成的环保包装材料",
    "关于时间尽头图书馆的科幻小说"
  ],
  es: [
    "Servicio de suscripción para plantas raras",
    "App para músicos locales",
    "Embalaje ecológico de algas",
    "Novela de ciencia ficción sobre una biblioteca eterna"
  ],
  ja: [
    "珍しい観葉植物のサブスクリプション",
    "地元のミュージシャンをつなぐアプリ",
    "海藻から作られた環境に優しいパッケージ",
    "時間の果てにある図書館についてのSF小説"
  ]
};

export const PLACEHOLDER_AVATAR = "https://picsum.photos/40/40";