import { Language } from './types';

export const TEXTS: Record<Language, Record<string, string>> = {
  en: {
    appTitle: "MuseSpark",
    welcome: "Turn your ideas into reality.",
    startChat: "Start New Inspiration",
    login: "Login / Register",
    history: "Chat History",
    myInspirations: "My Inspirations",
    settings: "Settings",
    send: "Send",
    placeholder: "Tell me about your idea...",
    analyzing: "Analyzing your idea...",
    generateNote: "Generate Plan",
    save: "Save to My Inspirations",
    update: "Update Inspiration",
    back: "Back",
    backToList: "Back to List",
    satisfied: "Satisfied & Save",
    notSatisfied: "Not Satisfied (Edit)",
    legalWarning: "Legal Disclaimer: This is AI generated advice, not legal counsel.",
    subscribe: "Upgrade to Pro",
    subscriptionDesc: "Get unlimited detailed analysis, image upload, and export options.",
    loginDesc: "Join millions of creators worldwide.",
    email: "Email",
    password: "Password",
    signIn: "Sign In",
    mvp: "MVP (Minimum Viable Product)",
    businessVal: "Business Value",
    risks: "Potential Risks",
    tags: "Tags",
    fullScreen: "Full Screen",
    minimize: "Minimize",
    delete: "Delete",
    viewNote: "View Note",
    emptyHistory: "No history yet",
    emptyInspirations: "No saved inspirations yet",
    generatedMap: "Auto-Generated Structure",
    uploadImage: "Upload Image",
    translating: "Translating content...",
    edit: "Edit",
    cancelEdit: "Cancel Edit",
    proFeature: "PRO Feature",
    subscribeModalTitle: "Unlock MuseSpark Pro",
    subscribeBtn: "Subscribe Now - $9.99/mo",
    deleteChatConfirm: "Are you sure you want to delete this chat?",
    deleteInspirationConfirm: "Are you sure you want to delete this saved inspiration?",
    mindMap: "Mind Map",
    mindMapHelper: "AI Assistant",
    mindMapPlaceholder: "Ask for a suggestion...",
    memo: "Memo"
  },
  zh: {
    appTitle: "灵感助手",
    welcome: "将您的灵感转化为现实。",
    startChat: "开始新灵感",
    login: "登录 / 注册",
    history: "聊天历史",
    myInspirations: "我的灵感",
    settings: "设置",
    send: "发送",
    placeholder: "告诉我你的想法...",
    analyzing: "正在分析您的想法...",
    generateNote: "生成方案",
    save: "保存到我的灵感",
    update: "更新灵感",
    back: "返回",
    backToList: "返回列表",
    satisfied: "满意并保存",
    notSatisfied: "不满意 (返回修改)",
    legalWarning: "法律免责声明：以上仅为一般性风险提示，并不构成法律意见。",
    subscribe: "升级专业版",
    subscriptionDesc: "获取无限详细分析、图片上传和导出选项。",
    loginDesc: "加入全球数百万创作者的行列。",
    email: "邮箱",
    password: "密码",
    signIn: "登录",
    mvp: "MVP (最小可行性产品)",
    businessVal: "商业价值",
    risks: "潜在风险",
    tags: "标签",
    fullScreen: "全屏",
    minimize: "最小化",
    delete: "删除",
    viewNote: "查看笔记",
    emptyHistory: "暂无历史记录",
    emptyInspirations: "暂无保存的灵感",
    generatedMap: "自动生成结构图",
    uploadImage: "上传图片",
    translating: "正在翻译内容...",
    edit: "编辑",
    cancelEdit: "取消编辑",
    proFeature: "专业版功能",
    subscribeModalTitle: "解锁 MuseSpark Pro",
    subscribeBtn: "立即订阅 - ¥28/月",
    deleteChatConfirm: "确定要删除此对话吗？",
    deleteInspirationConfirm: "确定要删除这条保存的灵感吗？",
    mindMap: "思维导图",
    mindMapHelper: "AI 助手",
    mindMapPlaceholder: "寻求建议...",
    memo: "备忘录"
  },
  es: {
    appTitle: "MuseSpark",
    welcome: "Convierte tus ideas en realidad.",
    startChat: "Nueva Inspiración",
    login: "Iniciar sesión",
    history: "Historial",
    myInspirations: "Mis Inspiraciones",
    settings: "Ajustes",
    send: "Enviar",
    placeholder: "Cuéntame tu idea...",
    analyzing: "Analizando...",
    generateNote: "Generar Plan",
    save: "Guardar",
    update: "Actualizar",
    back: "Volver",
    backToList: "Volver a la lista",
    satisfied: "Satisfecho y Guardar",
    notSatisfied: "No satisfecho (Editar)",
    legalWarning: "Aviso legal: Esto es un consejo generado por IA, no asesoramiento legal.",
    subscribe: "Suscribirse",
    subscriptionDesc: "Análisis ilimitado, subida de imágenes y exportación.",
    loginDesc: "Únete a millones de creadores.",
    email: "Correo",
    password: "Contraseña",
    signIn: "Entrar",
    mvp: "MVP (Producto Viable Mínimo)",
    businessVal: "Valor Comercial",
    risks: "Riesgos Potenciales",
    tags: "Etiquetas",
    fullScreen: "Pantalla Completa",
    minimize: "Minimizar",
    delete: "Eliminar",
    viewNote: "Ver Nota",
    emptyHistory: "Sin historial",
    emptyInspirations: "Sin inspiraciones guardadas",
    generatedMap: "Estructura Generada",
    uploadImage: "Subir Imagen",
    translating: "Traduciendo contenido...",
    edit: "Editar",
    cancelEdit: "Cancelar Edición",
    proFeature: "Función PRO",
    subscribeModalTitle: "Desbloquear MuseSpark Pro",
    subscribeBtn: "Suscribirse - $9.99/mes",
    deleteChatConfirm: "¿Estás seguro de que quieres eliminar este chat?",
    deleteInspirationConfirm: "¿Estás seguro de que deseas eliminar esta inspiración guardada?",
    mindMap: "Mapa Mental",
    mindMapHelper: "Asistente IA",
    mindMapPlaceholder: "Pedir sugerencia...",
    memo: "Memorándum"
  },
  ja: {
    appTitle: "MuseSpark",
    welcome: "アイデアを現実に変えましょう。",
    startChat: "新しいインスピレーション",
    login: "ログイン",
    history: "チャット履歴",
    myInspirations: "私のインスピレーション",
    settings: "設定",
    send: "送信",
    placeholder: "あなたのアイデアを教えてください...",
    analyzing: "分析中...",
    generateNote: "プラン生成",
    save: "保存",
    update: "更新",
    back: "戻る",
    backToList: "リストに戻る",
    satisfied: "保存する",
    notSatisfied: "編集する",
    legalWarning: "法的免責事項：これはAIによるアドバイスであり、法的助言ではありません。",
    subscribe: "プロ版にアップグレード",
    subscriptionDesc: "無制限の詳細分析、画像アップロード。",
    loginDesc: "世界中のクリエイターに参加しましょう。",
    email: "メール",
    password: "パスワード",
    signIn: "サインイン",
    mvp: "MVP (実用最小限の製品)",
    businessVal: "ビジネス価値",
    risks: "潜在的なリスク",
    tags: "タグ",
    fullScreen: "全画面",
    minimize: "最小化",
    delete: "削除",
    viewNote: "ノートを見る",
    emptyHistory: "履歴なし",
    emptyInspirations: "保存されたインスピレーションなし",
    generatedMap: "自動生成構造",
    uploadImage: "画像をアップロード",
    translating: "コンテンツを翻訳中...",
    edit: "編集",
    cancelEdit: "編集をキャンセル",
    proFeature: "PRO機能",
    subscribeModalTitle: "MuseSpark Proのロック解除",
    subscribeBtn: "購読する - ¥1000/月",
    deleteChatConfirm: "このチャットを削除してもよろしいですか？",
    deleteInspirationConfirm: "この保存されたインスピレーションを削除してもよろしいですか？",
    mindMap: "マインドマップ",
    mindMapHelper: "AI アシスタント",
    mindMapPlaceholder: "提案を求める...",
    memo: "メモ"
  }
};

export const PLACEHOLDER_AVATAR = "https://picsum.photos/40/40";